### ISSUE TITLE
periodic webpack stats error on refresh

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#176]
When refreshing a page repeatedly have been seeing this error popping up alongside 502 Bad Gateways:

`webpack_loader.exceptions.WebpackLoaderBadStatsError: The stats file does not contain valid data. Make sure webpack-bundle-tracker plugin is enabled and try to run webpack again.`

Full stack trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "./core/views.py", line 183, in server_error
    status=500)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.5/dist-packages/django_jinja/backend.py", line 106, in render
    return mark_safe(self.template.render(context))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "./core/templates/500.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "./core/templates/base.jinja", line 186, in top-level template code
    {{ render_bundle('styles', 'css') }}
  File "./core/templatetags/globals.py", line 21, in render_bundle
    return wl.render_bundle(bundle_name, extension, config, attrs)
  File "/usr/local/lib/python3.5/dist-packages/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle
    tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
  File "/usr/local/lib/python3.5/dist-packages/webpack_loader/utils.py", line 45, in get_as_tags
    bundle = _get_bundle(bundle_name, extension, config)
  File "/usr/local/lib/python3.5/dist-packages/webpack_loader/utils.py", line 23, in _get_bundle
    bundle = get_loader(config).get_bundle(bundle_name)
  File "/usr/local/lib/python3.5/dist-packages/webpack_loader/loader.py", line 99, in get_bundle
    "The stats file does not contain valid data. Make sure "
webpack_loader.exceptions.WebpackLoaderBadStatsError: The stats file does not contain valid data. Make sure webpack-bundle-tracker plugin is enabled and try to run webpack again.
```

**Comment by alee** [comment]
Seems to have been resolved in the switch from jest to karma. Closing for now
