### ISSUE TITLE
migration: raw_download uid KeyError

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#183]
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/code/drupal_migrator/management/commands/import_drupal_data.py", line 21, in handle
    load(directory)
  File "/code/drupal_migrator/database_migration.py", line 732, in load
    download_extractor.extract_all(model_id_map, model_version_id_map, user_id_map)
  File "/code/drupal_migrator/database_migration.py", line 638, in extract_all
    user_id = self._get_user_id(raw_download, user_id_map)
  File "/code/drupal_migrator/database_migration.py", line 616, in _get_user_id
    user = user_id_map.get(raw_download['uid'])
KeyError: 'uid'
```

**Comment by alee** [comment]
fixed in b509bd3aaf06e24b050dda997e294af28044aa21
