### ISSUE TITLE
fix first-run bug in setup_site

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#64]
Subsequent invocations are fine, seems to be an issue with deleting the original Wagtail 'home' Page.
```
root@7db341006adf:/code# invoke ss
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/code/drupal_migrator/management/commands/setup_site.py", line 84, in handle
    index_page = self.create_home_page()
  File "/code/drupal_migrator/management/commands/setup_site.py", line 80, in create_home_page
    root_page.add_child(instance=landing_page)
  File "/usr/local/lib/python3.5/dist-packages/treebeard/mp_tree.py", line 976, in add_child
    return MP_AddChildHandler(self, **kwargs).process()
  File "/usr/local/lib/python3.5/dist-packages/treebeard/mp_tree.py", line 359, in process
    newobj.path = self.node.get_last_child()._inc_path()
AttributeError: 'NoneType' object has no attribute '_inc_path'
```

**Comment by alee** [comment]
related to https://github.com/wagtail/wagtail/issues/3402
